apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
    - name: mongodb
      image: sameersbn/mongodb
      ports:
        - containerPort: 27017
          protocol: TCP
